package br.com.brainvest.api.curriculum;

import br.com.brainvest.api.api.ApiModels.LevelView;
import br.com.brainvest.api.api.ApiModels.OptionView;
import br.com.brainvest.api.api.ApiModels.QuestionView;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import org.springframework.stereotype.Component;

@Component
public class CurriculumCatalog {

    public record Option(String id, String text) {}

    public record Question(
            String id,
            String context,
            String prompt,
            String concept,
            List<Option> options,
            String correctOptionId,
            String correctFeedback,
            String incorrectFeedback) {}

    public record Level(
            int id,
            String title,
            String emoji,
            String tone,
            String description,
            String missionTitle,
            String missionBrief,
            String missionSummary,
            List<Question> questions) {}

    private final List<Level> levels = buildLevels();
    private final Map<String, Question> questions = levels.stream()
            .flatMap(level -> level.questions().stream())
            .collect(Collectors.toUnmodifiableMap(Question::id, Function.identity()));

    public List<Level> levels() {
        return levels;
    }

    public Level level(int levelId) {
        return levels.stream()
                .filter(level -> level.id() == levelId)
                .findFirst()
                .orElseThrow(() -> new CurriculumNotFoundException("N?vel n?o encontrado."));
    }

    public Question question(String questionId) {
        Question question = questions.get(questionId);
        if (question == null) throw new CurriculumNotFoundException("Quest?o n?o encontrada.");
        return question;
    }

    public int levelIdFor(String questionId) {
        return Integer.parseInt(questionId.substring(1, questionId.indexOf('-')));
    }

    public List<LevelView> publicLevels() {
        return levels.stream().map(level -> new LevelView(
                level.id(), level.title(), level.emoji(), level.tone(), level.description(),
                level.missionTitle(), level.missionBrief(), level.missionSummary(),
                level.questions().stream().map(question -> new QuestionView(
                        question.id(), question.context(), question.prompt(), question.concept(),
                        question.options().stream().map(option -> new OptionView(option.id(), option.text())).toList()
                )).toList()
        )).toList();
    }

    private static List<Option> options(String correctId, String correctText, String distractorOne, String distractorTwo) {
        List<String> distractors = List.of(distractorOne, distractorTwo);
        int distractorIndex = 0;
        java.util.ArrayList<Option> options = new java.util.ArrayList<>();
        for (String id : List.of("A", "B", "C")) {
            options.add(new Option(id, id.equals(correctId) ? correctText : distractors.get(distractorIndex++)));
        }
        return List.copyOf(options);
    }

    private static Question q(String id, String context, String prompt, String concept, String correctId,
                              String correctText, String distractorOne, String distractorTwo,
                              String correctFeedback, String incorrectFeedback) {
        return new Question(id, context, prompt, concept, options(correctId, correctText, distractorOne, distractorTwo),
                correctId, correctFeedback, incorrectFeedback);
    }

    private static Level level(int id, String title, String emoji, String tone, String description,
                               String missionTitle, String missionBrief, String missionSummary, Question... questions) {
        return new Level(id, title, emoji, tone, description, missionTitle, missionBrief, missionSummary, List.of(questions));
    }

    private static List<Level> buildLevels() {
        return List.of(
            level(1, "Minha vida financeira", "🧾", "mint",
                "Entenda para onde seu dinheiro vai e tome decisões melhores no dia a dia.",
                "Missão: o primeiro salário de Lucas",
                "Lucas tem 19 anos, recebe R$ 2.400 líquidos e gasta R$ 1.700 por mês. Ele quer se organizar sem deixar de aproveitar a vida.",
                "Lucas fechou o mes entendendo renda, gastos essenciais, desejos e juros do cartao. A ponte com CPA e clara: antes de produto financeiro, vem diagnostico, orcamento e decisao adequada ao objetivo.",
                q("l1-q1", "Organização do mês", "Qual é o primeiro passo para Lucas descobrir quanto pode guardar?", "Orçamento", "A",
                    "Anotar renda e gastos por um mês", "Investir todo o saldo da conta hoje", "Cancelar todos os momentos de lazer",
                    "Isso. Registrar entradas e saídas mostra o que já está comprometido e quanto cabe nos planos.",
                    "Antes de decidir quanto guardar ou cortar, Lucas precisa saber para onde o dinheiro está indo. Um orçamento começa com esse retrato."),
                q("l1-q2", "Necessidade ou desejo", "A geladeira de Lucas quebrou. Ele também queria trocar o celular, que ainda funciona. Qual gasto tende a ser prioridade?", "Priorização de gastos", "B",
                    "Resolver a geladeira e reavaliar o celular", "Trocar o celular, porque era o plano inicial", "Parcelar os dois sem olhar o orçamento",
                    "Boa. Necessidades urgentes vêm antes de desejos que podem esperar, considerando os recursos disponíveis.",
                    "Um plano pode mudar quando surge uma necessidade essencial. Adiar um desejo ajuda a evitar dívida e manter o orçamento sob controle."),
                q("l1-q3", "Cartão de crédito", "A fatura de Lucas é R$ 1.400 e vence hoje. Ele tem o valor na conta e nenhuma despesa urgente antes do próximo salário. O que tende a evitar juros?", "Pagamento da fatura", "C",
                    "Pagar a fatura integralmente", "Pagar o valor mínimo", "Esperar o próximo mês sem avisar o banco",
                    "Correto. Pagar o total até o vencimento evita financiar o saldo da fatura no crédito rotativo.",
                    "O pagamento mínimo não quita a fatura: o saldo restante pode gerar juros. Como Lucas tem o valor disponível, pagar o total evita esse financiamento."),
                q("l1-q4", "— Crédito rotativo", "Lucas não consegue pagar a fatura inteira neste mês. Antes de escolher pagar só o mínimo, qual comparação é mais importante?", "Custo do crédito", "A",
                    "O custo total do rotativo e de alternativas de renegociação ou crédito mais barato", "A quantidade de pontos que ele perderia no programa do cartão", "O limite disponível para fazer novas compras",
                    "Certo. O mínimo adia parte da dívida e pode acionar crédito caro. Comparar CET, prazo e valor total ajuda a decidir antes que a dívida cresça.",
                    "Pontos e limite não resolvem o custo da dívida. O primeiro passo é entender quanto cada alternativa cobra e se cabe no fluxo de caixa."),
                q("l1-q5", "Decisão do mês", "Depois de anotar os gastos, Lucas percebe que assinaturas pouco usadas consomem R$ 90 por mês. Qual decisão é mais consistente com o objetivo de guardar dinheiro?", "Ajuste de orçamento", "B",
                    "Cancelar ou rever as assinaturas e reservar o valor", "Ignorar os gastos pequenos porque não fazem diferença", "Usar o limite do cartão para cobrir o mês",
                    "Missão cumprida. Pequenos gastos recorrentes podem somar; direcionar o valor liberado para uma meta torna o plano concreto.",
                    "Gastos recorrentes se acumulam. Rever o que tem pouco valor para Lucas pode liberar dinheiro sem cortar o que é importante."),
                q("l1-q6", "Meta do mes", "Lucas decidiu guardar R$ 300 todo mes. Onde esse valor deve aparecer no planejamento dele?", "Meta financeira", "C",
                    "Como compromisso previsto antes dos gastos por impulso", "Apenas se sobrar dinheiro sem nenhum controle", "Como limite extra do cartao de credito",
                    "Boa. Quando a meta entra no orcamento, ela vira decisao planejada, nao sobra acidental.",
                    "Esperar sobrar parece facil, mas costuma falhar. A microdica e tratar a meta como compromisso do mes."),
                q("l1-q7", "— Prioridade entre dívidas", "Lucas tem duas dívidas em dia: uma com juros muito maiores e outra com juros baixos. Depois de manter os gastos essenciais, qual critério tende a orientar a prioridade de quitação?", "Priorização de dívidas", "A",
                    "Priorizar a dívida de maior custo, sem deixar de cumprir os pagamentos mínimos das demais", "Quitar primeiro a dívida com o maior número de parcelas, independentemente da taxa", "Fazer novas compras no cartão para conservar dinheiro em conta",
                    "Boa. Juros mais altos tendem a acelerar mais a dívida. A decisão também precisa respeitar vencimentos e necessidades essenciais.",
                    "O número de parcelas não mostra sozinho qual dívida pesa mais. Compare custos e evite aumentar o saldo enquanto organiza a quitação."),
                q("l1-q8", "Conexao CPA", "Antes de sugerir qualquer investimento para Lucas, qual informacao basica ainda precisa estar clara?", "Diagnostico financeiro", "B",
                    "Renda, gastos, dividas, reserva e objetivos", "A marca do banco que ele prefere", "O investimento que rendeu mais ontem",
                    "Exato. No atendimento financeiro, recomendacao adequada nasce do diagnostico do cliente.",
                    "Produto vem depois do contexto. A microdica e sempre perguntar: para quem, para quando e com qual risco?"),
                q("l1-q9", "— Gastos fixos e variáveis", "Qual gasto é mais útil classificar como variável ao montar o orçamento de Lucas?", "Mapeamento de gastos", "C",
                    "As refeições por delivery, que mudam conforme as escolhas do mês", "O aluguel, que tem valor contratado todo mês", "A parcela de um financiamento com valor definido em contrato",
                    "Isso. Gastos variáveis são os que podem oscilar com uso e decisão. Eles costumam oferecer espaço para ajustes conscientes.",
                    "Aluguel e parcela fixa normalmente já têm valor previsto. O delivery varia e deve aparecer como tal no planejamento."),
                q("l1-q10", "— Fluxo de caixa", "Em um mês, Lucas recebe R$ 2.400 e gasta R$ 2.550. O que esse resultado mostra?", "Resultado mensal", "A",
                    "Há déficit de R$ 150 que precisa ser coberto por ajuste, reserva ou crédito", "Há superávit de R$ 150 para investir", "O orçamento está equilibrado porque a diferença é pequena",
                    "Correto. Entrou menos do que saiu. Identificar cedo o déficit evita que ele vire uma dívida cara por acidente.",
                    "Mesmo um valor pequeno precisa ter origem clara. Se o padrão se repetir, o desequilíbrio se acumula."),
                q("l1-q11", "— Parcelamento", "Uma loja oferece um celular por R$ 1.200 à vista ou 12 parcelas de R$ 115. Antes de escolher, o que Lucas deve verificar?", "Custo efetivo do parcelamento", "B",
                    "O valor total parcelado e se as parcelas cabem no orçamento dos próximos meses", "Apenas se a parcela mensal parece pequena hoje", "Se o vendedor disse que é uma oportunidade única",
                    "Exato. Doze parcelas de R$ 115 somam R$ 1.380. A parcela cabe no mês, mas o compromisso e o custo total também importam.",
                    "Olhar só a parcela pode esconder o custo total e comprometer meses futuros. Compare o total e o impacto no orçamento."),
                q("l1-q12", "— Reserva e meta", "Lucas guardou R$ 1.000 para imprevistos e R$ 800 para um curso no próximo semestre. Por que separar esses valores no planejamento?", "Separação por objetivo", "C",
                    "Para saber qual parte pode ser usada em uma emergência sem abandonar automaticamente a meta do curso", "Para que os dois valores rendam exatamente da mesma forma", "Para evitar acompanhar quanto ele já guardou",
                    "Boa. Dar um propósito a cada valor evita misturar necessidades urgentes com objetivos planejados.",
                    "Objetivos podem exigir prazos e liquidez diferentes. Separar no planejamento dá clareza sobre o que cada saldo protege."),
                q("l1-q13", "— Juros compostos na prática", "Uma dívida permanece sem pagamento e gera juros sobre o saldo já acrescido de juros. Como esse mecanismo é chamado?", "Crescimento da dívida", "A",
                    "Juros compostos", "Desconto à vista", "Amortização antecipada",
                    "Certo. Com juros compostos, a base de cálculo cresce ao longo do tempo, por isso dívida cara pede ação rápida.",
                    "Amortizar reduz o saldo; não é o que acontece quando juros incidem sobre juros acumulados."),
                q("l1-q14", "— Custo de oportunidade", "Lucas usa R$ 300 que havia separado para uma viagem para comprar um item por impulso. Qual é o custo de oportunidade dessa decisão?", "Escolha financeira", "B",
                    "O que ele deixa de fazer com os R$ 300, como avançar na meta da viagem", "A garantia de que a viagem ficará mais barata depois", "O valor que o banco é obrigado a devolver",
                    "Isso. Toda escolha de uso do dinheiro exclui outro uso possível. Enxergar a troca ajuda a decidir com intenção.",
                    "Não há devolução automática nem garantia sobre preços futuros. O custo está na alternativa que foi deixada de lado."),
                q("l1-q15", "— Compras por impulso", "Para reduzir compras por impulso online, qual hábito é mais consistente com o orçamento de Lucas?", "Regra de decisão", "C",
                    "Esperar um prazo definido e conferir se a compra cabe na categoria de gastos do mês", "Comprar na hora para não perder qualquer desconto anunciado", "Aumentar o limite do cartão antes de decidir",
                    "Boa estratégia. Uma pequena pausa transforma uma decisão emocional em uma decisão comparada ao plano do mês.",
                    "Limite e urgência de promoção não demonstram que a compra cabe no orçamento. O critério precisa ser o plano financeiro."),
                q("l1-q16", "— Segurança em pagamentos", "Lucas recebe por mensagem um link para \"regularizar\" uma compra que não reconhece. Qual é a conduta mais segura antes de pagar?", "Prevenção a fraudes", "A",
                    "Acessar o aplicativo ou canal oficial da instituição por conta própria e conferir a informação", "Pagar pelo link para evitar bloqueio da conta", "Enviar senha e código de segurança para confirmar a identidade",
                    "Correto. Mensagens podem simular instituições. Conferir por um canal oficial e nunca compartilhar senhas ou códigos reduz o risco de golpe.",
                    "Links inesperados e pedidos de senha/código são sinais de alerta. A instituição não precisa desses dados por mensagem para validar você."),
                q("l1-q17", "— Limite não é renda", "O cartão de Lucas tem limite de R$ 5.000, mas seu orçamento livre do mês é de R$ 300. O que o limite representa?", "Uso responsável de crédito", "B",
                    "Possibilidade de crédito, não dinheiro disponível para gastar sem planejamento", "Renda extra garantida pelo banco", "Valor que ele deve usar todo mês para melhorar o score",
                    "Exato. Limite é uma forma de crédito que precisará ser paga depois. A referência de gasto é o orçamento, não o teto do cartão.",
                    "Usar todo o limite não melhora automaticamente o score e pode criar uma fatura incompatível com a renda."),
                q("l1-q18", "— Renda irregular", "A renda de Lucas passa a variar de R$ 2.000 a R$ 3.000 por mês. Qual abordagem torna o orçamento mais prudente?", "Orçamento com renda variável", "C",
                    "Planejar gastos fixos com uma referência conservadora e usar meses melhores para reserva e metas", "Assumir despesas fixas usando sempre o maior mês já recebido", "Parar de registrar gastos porque a renda não é estável",
                    "Boa. Quando a renda oscila, a segurança vem de não transformar picos temporários em compromissos permanentes.",
                    "Basear gastos fixos no melhor mês aumenta o risco de déficit nos meses mais fracos. Registrar continua sendo ainda mais importante."),
                q("l1-q19", "— Meta mensurável", "Qual meta financeira está mais bem definida para Lucas?", "Definição de meta", "A",
                    "\"Juntar R$ 1.800 até junho, reservando R$ 300 por mês\"", "\"Guardar algum dinheiro quando der\"", "\"Investir no que estiver rendendo mais\"",
                    "Certo. Valor, prazo e contribuição tornam a meta acompanhável e permitem ajustar o plano antes do prazo final.",
                    "Uma meta vaga não mostra se você está avançando. Defini-la permite medir e corrigir a rota."),
                q("l1-q20", "— Emergência ou consumo", "Qual situação combina melhor com o uso da reserva de emergência de Lucas?", "Uso da reserva", "B",
                    "Um conserto necessário para que ele continue trabalhando", "A troca de um celular que ainda funciona por um modelo recém-lançado", "Uma viagem que ele decidiu fazer porque encontrou promoção",
                    "Isso. Reserva existe para impactos imprevistos e relevantes, não para antecipar desejos de consumo.",
                    "Celular novo e viagem podem ser metas válidas, mas devem ter planejamento próprio para não consumir a proteção contra imprevistos."))
            ,
            level(2, "Antes de investir", "🛟", "coral",
                "Prepare uma base: objetivos, prazo, reserva, inflação e acesso ao dinheiro.",
                "Missão: a viagem e a reserva de Marina",
                "Marina está guardando dinheiro para uma viagem daqui a dois meses e também quer montar uma reserva para imprevistos.",
                "Marina separou dinheiro de curto prazo da reserva e percebeu que liquidez, prazo e inflacao mudam a escolha. Essa e a base para analisar adequacao antes de comparar rentabilidade.",
                q("l2-q1", "Objetivo e prazo", "Marina separou R$ 300 para uma viagem daqui a dois meses. O que ela deve considerar antes de escolher onde guardar?", "Objetivo e horizonte", "B",
                    "O prazo curto e a data em que vai precisar do dinheiro", "Apenas a maior rentabilidade anunciada", "Somente o nome mais conhecido do produto",
                    "Certo. O prazo do objetivo orienta quanto risco faz sentido e quando o dinheiro precisa estar disponível.",
                    "A maior taxa não basta. Para um objetivo próximo, a data de uso e a possibilidade de resgatar são essenciais."),
                q("l2-q2", "Reserva de emergência", "Marina começa a formar uma reserva para despesas inesperadas. Qual característica costuma ser importante para esse dinheiro?", "Liquidez", "C",
                    "Poder acessar o recurso quando surgir uma emergência", "Ficar bloqueado por vários anos em troca de uma taxa maior", "Variar muito de preço todos os dias",
                    "Exato. Liquidez é a facilidade e o prazo para transformar um investimento em dinheiro disponível.",
                    "Uma reserva pode ser necessária sem aviso. Por isso, liquidez e estabilidade são relevantes; carência longa pode não combinar com essa finalidade."),
                q("l2-q3", "Inflação", "Os preços sobem ao longo do ano. Se o dinheiro de Marina rende menos que essa alta, o que pode ocorrer?", "Poder de compra", "A",
                    "O saldo nominal cresce, mas compra menos coisas", "O poder de compra sempre aumenta", "A inflação cancela automaticamente os juros",
                    "Isso. O rendimento nominal não conta a história toda: é preciso considerar a variação dos preços para entender o ganho real.",
                    "O saldo pode aumentar em reais e ainda assim perder poder de compra se os preços subirem mais."),
                q("l2-q4", "Reserva adequada ao objetivo", "Marina tem R$ 10.000 reservados para emergências e analisa um produto com carência de dois anos. Qual ponto merece atenção primeiro?", "Liquidez e carência", "B",
                    "Se conseguirá acessar o dinheiro antes do fim da carência", "Se o produto tem o maior nome da prateleira", "Se a carência torna o investimento livre de riscos",
                    "Boa leitura. Uma carência longa pode conflitar com a finalidade de uma reserva que talvez precise ser usada rapidamente.",
                    "Carência não significa ausência de risco nem combina automaticamente com qualquer objetivo. Para a reserva, disponibilidade é central."),
                q("l2-q5", "— Juros simples e compostos", "Dois investimentos têm a mesma taxa de 1% ao mês. Em qual situação os juros compostos fazem diferença em relação aos juros simples?", "Capitalização", "C",
                    "Quando os rendimentos de cada período passam a compor a base de cálculo dos períodos seguintes", "Quando o investimento não tem prazo de resgate", "Quando a taxa é informada em porcentagem em vez de reais",
                    "Correto. Nos juros compostos, o rendimento também rende nos períodos seguintes. O efeito aumenta com taxa e tempo.",
                    "Liquidez e unidade de medida não definem o regime de capitalização. O ponto é a incidência de juros sobre o saldo acumulado."),
                q("l2-q6", "— Selic e CDI", "Marina vê um CDB que paga 100% do CDI. O que essa informação indica?", "Taxas de referência", "A",
                    "A remuneração acompanha uma taxa de referência ligada às operações interbancárias, conforme as regras do produto", "O banco pagará exatamente 100% de lucro sobre o valor aplicado", "O investimento terá sempre o mesmo rendimento nominal de um título prefixado",
                    "Boa. \"100% do CDI\" descreve um indexador de remuneração, não uma promessa de dobrar o dinheiro.",
                    "O percentual é aplicado sobre a taxa CDI do período. A rentabilidade efetiva depende da taxa, do prazo e da tributação aplicável."),
                q("l2-q7", "Ganho real", "Se uma aplicacao rende 8% no ano e a inflacao fica em 6%, o que Marina deve perceber?", "Rentabilidade real", "B",
                    "O ganho real aproximado e menor que o ganho nominal", "O ganho real e sempre igual ao rendimento anunciado", "A inflacao nao interfere no poder de compra",
                    "Correto. Rentabilidade real olha o que sobra depois da perda de poder de compra.",
                    "O numero anunciado e nominal. A microdica e sempre perguntar: isso supera a inflacao?"),
                q("l2-q8", "— Quem supervisiona o quê?", "Qual órgão tem papel central na supervisão do mercado de valores mobiliários, como ações e fundos de investimento?", "Sistema Financeiro Nacional", "C",
                    "Comissão de Valores Mobiliários (CVM)", "Fundo Garantidor de Créditos (FGC)", "Conselho Monetário Nacional (CMN)",
                    "Certo. A CVM supervisiona o mercado de valores mobiliários. O FGC é um mecanismo de garantia para créditos elegíveis; o CMN é órgão normativo.",
                    "As três siglas têm funções diferentes. A pergunta trata de supervisão de valores mobiliários, campo da CVM."),
                q("l2-q9", "— Papel do CMN", "Qual descrição representa melhor o papel do Conselho Monetário Nacional (CMN)?", "Órgãos normativos", "A",
                    "Definir diretrizes gerais das políticas monetária, creditícia e cambial", "Administrar diariamente todos os fundos de investimento do país", "Garantir automaticamente qualquer aplicação financeira feita por pessoa física",
                    "Isso. O CMN é um órgão normativo do Sistema Financeiro Nacional; ele não administra fundos nem substitui as regras de garantia do FGC.",
                    "Funções de norma, supervisão, operação e garantia são diferentes. O CMN atua na definição de diretrizes gerais."),
                q("l2-q10", "— Papel do Banco Central", "Qual atividade está mais associada ao Banco Central do Brasil?", "Supervisão bancária", "B",
                    "Supervisionar instituições financeiras e executar diretrizes da política monetária", "Escolher as empresas cujas ações podem subir na bolsa", "Vender cotas de fundos diretamente ao público",
                    "Correto. O Banco Central integra a supervisão do sistema financeiro e atua na execução da política monetária.",
                    "A bolsa e as instituições distribuidoras têm outros papéis. O Banco Central não seleciona ações vencedoras nem vende fundos ao público."),
                q("l2-q11", "— Copom e taxa Selic", "Quando o Copom altera a meta da taxa Selic, qual efeito pode ocorrer na economia?", "Política monetária", "C",
                    "Pode influenciar o custo do crédito, a remuneração de aplicações e decisões de consumo e investimento", "Define o preço de cada ação negociada na bolsa no mesmo instante", "Garante que a inflação desapareça imediatamente",
                    "Boa. A Selic é uma referência relevante para juros na economia, mas seus efeitos não são instantâneos nem determinam cada ativo isoladamente.",
                    "A decisão do Copom tem alcance macroeconômico. Ela não fixa preços de ações nem elimina automaticamente a inflação."),
                q("l2-q12", "— Inflação e retorno real", "Marina teve rendimento nominal de 10% no ano, enquanto a inflação foi de 8%. Qual leitura é mais correta?", "Retorno real", "A",
                    "Houve ganho de poder de compra, mas menor que 10%", "O ganho real foi exatamente 18%", "A inflação não importa porque o saldo subiu",
                    "Certo. A inflação reduz parte do ganho nominal. O retorno real exato considera a relação entre as duas taxas, e é próximo de 1,9% nesse exemplo.",
                    "Somar inflação ao rendimento não mede ganho real. Saldo maior não garante automaticamente maior poder de compra."),
                q("l2-q13", "— Taxa prefixada", "Em um investimento prefixado mantido até o vencimento, o que foi definido no momento da aplicação?", "Indexadores", "B",
                    "A regra de remuneração em taxa previamente conhecida, conforme condições do título", "O valor da inflação de todos os anos seguintes", "O preço de venda antecipada em qualquer data futura",
                    "Isso. Prefixado significa que a taxa foi estabelecida na contratação. Se houver venda antes do vencimento, o preço pode variar.",
                    "A taxa definida não congela inflação nem preço de venda antecipada. Prazo e marcação a mercado continuam relevantes."),
                q("l2-q14", "— Taxa pós-fixada", "Um produto pós-fixado remunera \"100% do CDI\". Qual variável ainda não está conhecida em valor nominal no dia da aplicação?", "Indexadores", "C",
                    "A taxa CDI que prevalecerá ao longo do período", "O percentual de 100% informado pelo emissor", "O valor inicialmente aplicado por Marina",
                    "Exato. A regra é conhecida, mas o indexador varia ao longo do tempo. Por isso o resultado nominal final não é fixado no primeiro dia.",
                    "O percentual e o valor aplicado são conhecidos. O que muda é a taxa de referência usada na remuneração."),
                q("l2-q15", "— Risco de crédito", "Qual situação descreve risco de crédito em um investimento?", "Tipos de risco", "A",
                    "O emissor não conseguir pagar o que deve ao investidor", "O dinheiro demorar para estar disponível no resgate", "O preço do ativo oscilar com mudanças de juros ou mercado",
                    "Correto. Risco de crédito está ligado à capacidade de pagamento do emissor ou devedor.",
                    "Demora de resgate é risco de liquidez; oscilação de preço é risco de mercado. Eles podem coexistir, mas são conceitos distintos."),
                q("l2-q16", "— Risco de liquidez", "Qual situação descreve risco de liquidez?", "Tipos de risco", "B",
                    "Precisar do dinheiro e não conseguir resgatar ou vender rapidamente sem impacto relevante no valor", "O emissor declarar que não pagará a dívida", "A inflação reduzir o poder de compra do saldo",
                    "Boa. Liquidez trata da facilidade, prazo e possível custo para transformar um investimento em recursos disponíveis.",
                    "Inadimplência é risco de crédito; perda de poder de compra se relaciona à inflação. Liquidez é a disponibilidade de caixa."),
                q("l2-q17", "— Risco de mercado", "Um título negociado antes do vencimento cai de preço após uma alta dos juros de mercado. Que risco se materializou?", "Tipos de risco", "C",
                    "Risco de mercado", "Risco de cadastro", "Risco de garantia do FGC",
                    "Certo. Variações em taxas e preços de mercado podem alterar o valor de negociação de um ativo antes do vencimento.",
                    "O ponto do caso é a oscilação de preço por condições de mercado, não o cadastro nem uma regra de garantia."),
                q("l2-q18", "— Objetivo e prazo", "Marina tem duas metas: intercâmbio em 18 meses e aposentadoria em 30 anos. Qual informação muda de forma mais direta a análise de liquidez e oscilação aceitável?", "Adequação inicial", "A",
                    "O horizonte de cada objetivo", "A cor do aplicativo usado para investir", "A marca mais anunciada nas redes sociais",
                    "Isso. Prazos diferentes mudam a necessidade de acesso ao dinheiro e o tempo disponível para atravessar oscilações.",
                    "Marca e interface não definem adequação. A data em que o dinheiro será necessário é uma informação central."),
                q("l2-q19", "— Poder de compra", "Se o preço de uma cesta de compras sobe de R$ 100 para R$ 110, qual foi a variação percentual do preço?", "Inflação", "B",
                    "10%", "11%", "90%",
                    "Correto. O aumento foi de R$ 10 sobre uma base de R$ 100. Esse é o tipo de mudança que a inflação procura medir em conjuntos de preços.",
                    "A variação é calculada sobre o preço inicial: 10 dividido por 100, ou 10%."),
                q("l2-q20", "— Comparação responsável", "Marina compara duas aplicações. Qual conjunto de informações é suficiente para começar uma comparação responsável?", "Decisão de investimento", "C",
                    "Rentabilidade ou indexador, prazo, liquidez, riscos, custos e tributação aplicável", "Só a taxa anunciada em letras grandes", "Apenas a recomendação de uma pessoa influente na internet",
                    "Boa. A taxa sozinha não mostra se o produto cabe no objetivo. Comparar exige olhar retorno junto com acesso, risco e custos.",
                    "Recomendação e taxa podem iniciar uma pesquisa, mas não substituem as características que determinam adequação."))
            ,
            level(3, "Começando a investir", "🌱", "butter",
                "Conheça renda fixa, títulos públicos, CDBs, fundos e renda variável.",
                "Missão: escolher sem cair no nome bonito",
                "Depois de organizar a reserva, Pedro compara produtos de investimento. Cada escolha precisa combinar com o funcionamento e o prazo do produto.",
                "Pedro saiu do nome do produto e passou a olhar emissor, regra de remuneracao, cotas, prazo e risco. E esse olhar que prepara para a linguagem de investimentos da CPA.",
                q("l3-q1", "— O que renda fixa quer dizer", "Por que chamar um investimento de renda fixa não significa que ele é livre de risco?", "Renda fixa", "C",
                    "Porque a regra de remuneração pode ser conhecida, mas emissor, liquidez e preço de venda antecipada ainda importam", "Porque todo produto de renda fixa tem o mesmo preço de uma ação", "Porque renda fixa não tem prazo nem emissor",
                    "Correto. Renda fixa descreve a forma de remuneração. Ela não elimina riscos de crédito, liquidez ou oscilação em venda antecipada.",
                    "A regra de rendimento não apaga as características do emissor, do prazo e do mercado. Elas precisam ser avaliadas antes da aplicação."),
                q("l3-q2", "CDB", "Um CDB é emitido por qual tipo de instituição?", "Certificado de Depósito Bancário", "A",
                    "Um banco ou outra instituição financeira emissora", "O Tesouro Nacional em nome do governo federal", "Uma bolsa de valores em nome do investidor",
                    "Isso. No CDB, o investidor empresta recursos à instituição emissora conforme as condições contratadas.",
                    "CDB significa Certificado de Depósito Bancário: é emitido por uma instituição financeira, não pelo Tesouro ou pela bolsa."),
                q("l3-q3", "Tesouro Direto", "Ao comprar um título público pelo Tesouro Direto, a quem o investidor está emprestando recursos?", "Títulos públicos", "B",
                    "Ao governo federal, conforme as regras do título", "A uma empresa privada escolhida pela corretora", "A outros investidores sem intermediação",
                    "Certo. Títulos públicos são emitidos pelo Tesouro Nacional; cada título tem regras próprias de remuneração e vencimento.",
                    "No Tesouro Direto, o título é público e emitido pelo Tesouro Nacional. Ainda é preciso entender prazo e oscilação em resgates antecipados."),
                q("l3-q4", "Fundos de investimento", "O que representa uma cota de um fundo de investimento?", "Fundos e cotas", "C",
                    "Uma fração do patrimônio do fundo", "Uma promessa de rentabilidade fixa do administrador", "Um depósito bancário automaticamente coberto pelo FGC",
                    "Exato. Ao investir, a pessoa adquire cotas, e o resultado depende dos ativos e das regras do fundo.",
                    "Cota é uma fração do patrimônio do fundo. Fundo não é depósito bancário e não oferece garantia de rentabilidade por definição."),
                q("l3-q5", "Renda variável", "Uma ação pode subir ou cair de preço. O que isso indica para quem investe?", "Renda variável", "A",
                    "O retorno pode variar e há possibilidade de perdas", "O preço só muda quando a empresa distribui dividendos", "A ação tem vencimento e devolve sempre o valor aplicado",
                    "Missão concluída. Na renda variável, preços e resultados podem oscilar; entender isso vem antes de investir.",
                    "O preço das ações varia no mercado e não há devolução garantida do valor investido. Oscilação e perdas fazem parte dos riscos."),
                q("l3-q6", "Marcacao a mercado", "Pedro ouviu que um titulo publico pode oscilar antes do vencimento. O que isso significa?", "Marcacao a mercado", "B",
                    "O preco pode variar se ele vender antes do vencimento", "O governo cancela automaticamente o titulo", "Todo titulo publico perde dinheiro no vencimento",
                    "Certo. Antes do vencimento, o preco pode oscilar; no vencimento valem as regras do titulo.",
                    "Oscilacao nao e cancelamento. A microdica e separar venda antecipada de carregamento ate o vencimento."),
                q("l3-q7", "— Taxas em fundos", "Quando prevista no regulamento, em que situação uma taxa de performance de um fundo pode ser cobrada?", "Taxa de administração e performance", "C",
                    "Conforme as regras do fundo e o resultado em relação ao parâmetro de referência definido", "Sempre que qualquer pessoa solicitar resgate", "Como substituta de todos os impostos que incidiriam sobre o investimento",
                    "Boa. Taxas de administração e de performance têm regras diferentes. É preciso ler regulamento, lâmina e documentos do fundo.",
                    "Resgate e impostos não definem por si só uma taxa de performance. Ela depende das condições previstas para o fundo."),
                q("l3-q8", "— Limite do FGC", "Considerando a garantia ordinária do FGC, qual é o limite máximo por CPF ou CNPJ para créditos elegíveis em uma mesma instituição ou conglomerado financeiro?", "Cobertura do FGC", "A",
                    "R$ 250 mil, observadas as regras aplicáveis", "R$ 1 milhão por produto, sem considerar a instituição emissora", "Não existe limite para CDB, LCI e LCA",
                    "Certo. A regra considera instituição ou conglomerado e créditos elegíveis. Há também um teto global de pagamentos de R$ 1 milhão a cada quatro anos.",
                    "A garantia não é ilimitada nem calculada por produto isolado. É preciso verificar elegibilidade, titularidade e conglomerado."),
                q("l3-q9", "— CDB pós-fixado", "Um CDB rende 110% do CDI. Se o CDI aumentar durante o período, o que tende a ocorrer com a remuneração bruta do CDB, mantidas as demais condições?", "CDB e indexador", "B",
                    "Ela tende a acompanhar a alta do CDI por usar esse indexador", "Ela permanece necessariamente igual à taxa do dia da aplicação", "Ela deixa de depender do banco emissor",
                    "Isso. O percentual contratado incide sobre o CDI de cada período. O risco de crédito do emissor continua existindo.",
                    "\"110%\" não fixa uma taxa nominal para todo o período. Ele relaciona o rendimento ao CDI que vier a ocorrer."),
                q("l3-q10", "— CDB e debênture", "Qual diferença básica existe entre um CDB e uma debênture?", "Emissor de títulos de dívida", "C",
                    "O CDB é dívida de instituição financeira; a debênture é dívida emitida por empresa", "O CDB é uma ação e a debênture é uma cota de fundo", "Ambos são emitidos exclusivamente pelo Tesouro Nacional",
                    "Correto. Em ambos os casos, importa avaliar quem emite e quais são as condições. A natureza do emissor muda a análise de risco e garantia.",
                    "Nem CDB nem debênture são ação, cota de fundo ou título público. São instrumentos de dívida com emissores distintos."),
                q("l3-q11", "— LCI e LCA", "LCI e LCA são títulos emitidos por instituições financeiras para captar recursos ligados, respectivamente, aos setores imobiliário e do agronegócio. Além da taxa, qual ponto deve ser verificado antes de investir?", "Títulos bancários", "A",
                    "Prazo, possibilidade de resgate, emissor e regras de garantia aplicáveis", "Apenas se as letras têm a mesma sigla do banco", "Se existe garantia de poder vender a qualquer hora pelo mesmo preço",
                    "Boa. Produtos semelhantes no nome podem ter prazos e condições diferentes. A análise precisa ir além da taxa divulgada.",
                    "Sigla e promessa de liquidez não substituem a leitura das condições. Emissor, carência e garantia são informações centrais."),
                q("l3-q12", "— O que o FGC não cobre", "Qual produto abaixo não conta com a garantia ordinária do FGC?", "Produtos elegíveis ao FGC", "B",
                    "Cota de fundo de investimento", "CDB elegível emitido por instituição associada", "LCI elegível emitida por instituição associada",
                    "Certo. Fundos têm patrimônio próprio e riscos ligados à sua carteira; não são depósitos bancários cobertos pelo FGC.",
                    "CDB e LCI podem ser elegíveis, observadas regras e limites. Cotas de fundos não fazem parte da garantia ordinária."),
                q("l3-q13", "— Tesouro Selic", "O Tesouro Selic tem remuneração ligada a qual referência principal?", "Títulos públicos pós-fixados", "C",
                    "À taxa Selic, conforme as regras do título", "Ao lucro distribuído por empresas listadas", "Ao aluguel de imóveis de um fundo imobiliário",
                    "Isso. É um título público pós-fixado. Ainda vale conferir prazo, condições de negociação e objetivo antes de utilizá-lo.",
                    "Lucros de empresas e aluguéis de imóveis pertencem a outros tipos de ativos. O indexador deste título é a Selic."),
                q("l3-q14", "— Tesouro IPCA+", "O que caracteriza, em linhas gerais, um título Tesouro IPCA+ mantido até o vencimento?", "Títulos públicos indexados à inflação", "A",
                    "Uma remuneração composta por variação do IPCA e taxa real definida nas condições do título", "Uma rentabilidade igual à de qualquer CDB, independentemente do prazo", "Uma garantia do FGC sobre cotas de fundo",
                    "Correto. A estrutura procura combinar inflação medida pelo IPCA e uma taxa real. Venda antecipada pode sofrer oscilação de preço.",
                    "Tesouro IPCA+ não é CDB nem produto coberto pelo FGC. O prazo e a marcação a mercado continuam importantes."),
                q("l3-q15", "— Resgate antecipado de título público", "Pedro compra um título público de prazo longo e precisa vendê-lo antes do vencimento. Qual preço receberá?", "Marcação a mercado", "B",
                    "O preço de mercado disponível na recompra naquele momento", "Sempre exatamente o valor inicialmente aplicado mais a taxa contratada", "O preço que Pedro escolher no aplicativo",
                    "Exato. A remuneração prevista vale se o título for levado até o vencimento. Antes disso, a venda ocorre a preço de mercado.",
                    "O preço de venda antecipada não é escolhido pelo investidor nem necessariamente igual ao valor de vencimento."),
                q("l3-q16", "— Funções em um fundo", "Em um fundo de investimento, quem toma as decisões de compra e venda dos ativos conforme a política do fundo?", "Administração e gestão", "C",
                    "A gestora", "Cada cotista individualmente", "O FGC",
                    "Certo. A gestora administra a carteira dentro da política de investimento. Outros prestadores, como administradora e custodiante, têm funções próprias.",
                    "Cotistas não escolhem cada ativo do fundo, e o FGC não gere fundos. A atividade de gestão cabe à gestora."),
                q("l3-q17", "— Cotização e liquidação", "Um fundo informa \"cotização D+5 e pagamento D+2 após a cotização\". Por que Pedro deve olhar os dois prazos?", "Prazo de resgate em fundos", "A",
                    "Porque eles ajudam a estimar quando o valor do resgate estará efetivamente disponível", "Porque D+5 garante pagamento imediato no mesmo dia", "Porque prazos de resgate só interessam à administradora",
                    "Boa. Cotização define a data de conversão das cotas; a liquidação indica quando o dinheiro é pago. Ambos afetam liquidez.",
                    "O prazo não é instantâneo só por aparecer como \"D+\". Para um objetivo próximo, é necessário compreender toda a sequência."),
                q("l3-q18", "— ETF", "O que caracteriza um ETF, em linhas gerais?", "Fundos negociados em bolsa", "B",
                    "Fundo cujas cotas são negociadas em bolsa e que normalmente busca acompanhar uma referência de mercado", "Título bancário coberto automaticamente pelo FGC", "Empréstimo feito diretamente ao governo federal",
                    "Isso. ETF é um fundo negociado em bolsa e pode oferecer exposição diversificada, mas continua sujeito aos riscos dos ativos e à variação de preço.",
                    "ETF não é CDB nem título público. A negociação de cotas em bolsa é uma de suas características centrais."),
                q("l3-q19", "— FII", "Um fundo imobiliário investe em imóveis ou títulos do setor imobiliário. Qual risco pode afetar uma cota de FII?", "Fundos imobiliários", "C",
                    "Vacância, crédito, liquidez e variação de preço no mercado", "Apenas a taxa Selic, sem nenhuma outra influência", "Nenhum risco, porque imóveis sempre se valorizam",
                    "Correto. O tipo de ativo e a forma de negociação trazem riscos específicos. Renda distribuída e valorização não são garantidas.",
                    "Imóveis e fundos imobiliários podem sofrer vacância, mudanças de juros, preço e liquidez. Não existe valorização automática."),
                q("l3-q20", "— Ações e dividendos", "Uma empresa distribuiu dividendos no passado. O que isso permite concluir sobre o próximo período?", "Renda variável", "A",
                    "Não garante nova distribuição nem valor igual; a decisão e os resultados podem mudar", "Garante que a ação não poderá cair de preço", "Transforma a ação em título de renda fixa",
                    "Boa. Histórico ajuda a entender a empresa, mas não é promessa de dividendos nem de valorização futura.",
                    "Ações continuam sendo renda variável. Dividendos anteriores não eliminam riscos de preço ou de resultado da empresa."))
            ,
            level(4, "Pensando como investidor", "🧭", "ink",
                "Conecte perfil, risco, retorno, diversificação e horizonte de investimento.",
                "Missão: o plano de investimento de Bia",
                "Bia tem objetivos com prazos diferentes e está conhecendo alternativas. Seu desafio é avaliar adequação, não perseguir a maior taxa isoladamente.",
                "Bia aprendeu que risco, retorno, diversificacao, perfil e horizonte precisam conversar entre si. A boa decisao nao e a mais chamativa: e a que combina com a pessoa e com o prazo.",
                q("l4-q1", "Risco e retorno", "Uma oferta promete retorno potencial maior, mas pode oscilar bastante. O que Bia deve entender?", "Relação entre risco e retorno", "A",
                    "Maior retorno potencial pode vir acompanhado de maior risco", "O retorno maior elimina a chance de perda", "O risco importa apenas depois do vencimento",
                    "Certo. Potencial de retorno precisa ser analisado junto com os riscos e a capacidade de suportar perdas.",
                    "Uma possibilidade de retorno maior não elimina riscos. Avaliar ambos é parte da decisão, antes e durante o investimento."),
                q("l4-q2", "Diversificação", "Por que distribuir os investimentos entre alternativas diferentes pode ajudar?", "Diversificação", "B",
                    "Pode reduzir a concentração em uma única fonte de risco", "Garante lucro em qualquer cenário", "Torna desnecessário conhecer os produtos",
                    "Isso. Diversificar pode reduzir concentração, embora não elimine todos os riscos nem garanta lucro.",
                    "Diversificação distribui exposições, mas não torna uma carteira livre de risco ou de perdas."),
                q("l4-q3", "— Perfil não é rótulo", "Bia se declara \"arrojada\", mas precisará usar grande parte do dinheiro para uma cirurgia em seis meses. O que uma análise de adequação deve fazer?", "Suitability", "C",
                    "Considerar objetivo, prazo, necessidade de liquidez, situação financeira e conhecimento, além do rótulo escolhido", "Usar somente a palavra \"arrojada\" para definir todos os produtos", "Desconsiderar a data da cirurgia porque o perfil não muda",
                    "Correto. Perfil não substitui contexto. Uma parcela necessária em breve pode ter necessidade diferente da carteira de longo prazo.",
                    "A autodeclaração é apenas uma informação. Adequação exige cruzar riscos do produto com objetivo, prazo e situação financeira."),
                q("l4-q4", "Horizonte de investimento", "Bia precisará pagar um curso daqui a seis meses. Por que o prazo deve influenciar a escolha?", "Horizonte e adequação", "A",
                    "Porque ela pode não ter tempo para esperar uma recuperação após oscilações", "Porque um prazo curto garante retorno alto", "Porque o vencimento nunca importa em investimentos",
                    "Boa. O horizonte afeta a capacidade de lidar com oscilações e a compatibilidade com o momento do gasto.",
                    "Um objetivo próximo reduz o tempo para lidar com oscilações ou esperar um vencimento. Prazo não garante retorno."),
                q("l4-q5", "— Produto adequado", "Um produto tem alto potencial de retorno, mas também alta oscilação e prazo de resgate incompatível com a meta de Bia. Qual conclusão é mais técnica?", "Compatibilidade entre produto e objetivo", "B",
                    "A taxa potencial não basta; o produto pode ser inadequado para essa parcela da meta", "Retorno potencial alto torna qualquer produto adequado", "Liquidez e oscilação só devem ser avaliadas depois da aplicação",
                    "Boa. Adequação é a compatibilidade entre características do produto e necessidade da pessoa, não uma competição por taxa.",
                    "Avaliar só depois da aplicação é tarde. Liquidez, risco e prazo precisam entrar antes da decisão."),
                q("l4-q6", "— Capacidade de assumir risco", "Bia diz que aceitaria ver a carteira cair, mas não tem reserva e depende daquele dinheiro para despesas básicas. O que isso revela?", "Capacidade versus tolerância", "C",
                    "A tolerância declarada pode ser maior que sua capacidade financeira de suportar perdas", "A falta de reserva aumenta automaticamente a capacidade de risco", "Só a idade define a capacidade de assumir risco",
                    "Isso. Vontade de correr risco e condição financeira para absorver perdas são dimensões diferentes da análise.",
                    "Sem reserva, uma oscilação pode obrigar a venda em momento ruim. Idade isolada não retrata esse risco."),
                q("l4-q7", "Concentracao", "Bia quer colocar todo o dinheiro em um unico ativo porque ele subiu muito. Qual risco aparece?", "Risco de concentracao", "A",
                    "Ficar dependente demais do desempenho de uma unica alternativa", "Garantir retorno maior por ter conviccao", "Eliminar risco por escolher algo conhecido",
                    "Isso. Concentracao pode ampliar perdas se aquele ativo for mal.",
                    "Alta recente seduz, mas nao elimina risco. Pense em diversificacao e objetivo."),
                q("l4-q8", "Rebalanceamento", "Depois de meses, a carteira de Bia ficou mais arriscada do que o planejado. O que pode fazer sentido?", "Acompanhamento da carteira", "B",
                    "Reavaliar e rebalancear conforme objetivo e perfil", "Nunca revisar a carteira depois da primeira compra", "Comprar mais risco sem olhar o plano",
                    "Boa. Planejamento tambem exige acompanhamento e ajustes.",
                    "Carteira muda com o mercado. A microdica e comparar a carteira atual com o plano original."),
                q("l4-q9", "— Correlação e diversificação", "Por que combinar ativos que não se comportam sempre do mesmo jeito pode ajudar a diversificar uma carteira?", "Correlação de ativos", "C",
                    "Porque perdas de um ativo podem ser parcialmente compensadas por comportamentos diferentes de outros", "Porque isso garante retorno positivo todo mês", "Porque deixa de ser necessário entender os riscos individuais",
                    "Correto. Diversificação busca reduzir dependência de uma única fonte de risco. Ela não elimina perdas nem dispensa análise.",
                    "Ter vários ativos parecidos pode manter a carteira concentrada. A diversidade de comportamentos é parte importante da proteção."),
                q("l4-q10", "— Diversificar não é só ter muitos nomes", "Bia compra CDB, LCI e LCA emitidos pelo mesmo conglomerado financeiro. O que ela precisa observar?", "Risco de concentração", "A",
                    "Continua exposta ao mesmo conglomerado e aos limites de garantia aplicáveis", "Eliminou o risco de crédito por ter três siglas diferentes", "Passou a ter três garantias ilimitadas e independentes",
                    "Boa. Diversificar produtos não é o mesmo que diversificar emissores. Em garantia ordinária, o conglomerado também importa.",
                    "Siglas diferentes podem apontar para o mesmo emissor ou grupo econômico. É preciso conferir quem está por trás do produto."),
                q("l4-q11", "— Alocação por objetivos", "Bia divide sua carteira em uma parcela para emergência, outra para curso em dois anos e outra para aposentadoria. Que princípio ela está aplicando?", "Asset allocation", "B",
                    "Alocar recursos conforme objetivos, prazos, liquidez e risco de cada parcela", "Escolher um único produto para todos os objetivos, sem comparar características", "Investir cada parcela no ativo com maior alta do último mês",
                    "Exato. Separar por finalidade permite avaliar cada recurso pelo prazo e necessidade que ele realmente tem.",
                    "Uma única aplicação pode não atender simultaneamente emergência, objetivo próximo e horizonte de décadas."),
                q("l4-q12", "— Caixa para curto prazo", "Bia tem um pagamento inadiável em 45 dias. Qual risco ela reduz ao não depender de um ativo que pode oscilar muito até essa data?", "Gestão de liquidez", "C",
                    "O risco de precisar vender com perda ou sem liquidez em um momento desfavorável", "O risco de o dinheiro render exatamente zero em qualquer cenário", "O risco de o objetivo deixar de ter uma data",
                    "Isso. Prazo curto reduz o tempo disponível para esperar uma recuperação de preço ou um resgate longo.",
                    "O problema não é a existência da data, e sim a incompatibilidade entre a data e a forma de acesso ao investimento."),
                q("l4-q13", "— Mercado primário e secundário", "Quando uma empresa emite novas ações e recebe os recursos dessa emissão, a operação ocorre principalmente em qual mercado?", "Mercado de capitais", "A",
                    "Mercado primário", "Mercado secundário", "Mercado de câmbio",
                    "Certo. No mercado primário, recursos da emissão vão para a empresa. No secundário, investidores negociam títulos entre si.",
                    "Comprar e vender ações já emitidas entre investidores é mercado secundário. A emissão nova pela companhia é mercado primário."),
                q("l4-q14", "— Papel da B3", "Qual é uma função associada à B3 no mercado brasileiro?", "Infraestrutura de mercado", "B",
                    "Oferecer infraestrutura para negociação, registro, compensação e liquidação de ativos, conforme o mercado", "Definir a meta oficial de inflação do país", "Garantir que todas as ações tenham valorização positiva",
                    "Correto. A B3 é uma infraestrutura de mercado; ela não formula política econômica nem garante rentabilidade.",
                    "Meta de inflação e retorno de ações não são funções da B3. A instituição atua na infraestrutura do mercado financeiro e de capitais."),
                q("l4-q15", "— Prazo e sensibilidade a juros", "Mantidas as demais condições, um título prefixado de prazo mais longo tende a ser mais sensível a mudanças nas taxas de juros do que um título curto. Por quê?", "Duration e risco de mercado", "C",
                    "Porque há mais fluxos futuros cujo valor presente reage à mudança de juros", "Porque títulos longos não têm emissor", "Porque prazo longo elimina a marcação a mercado",
                    "Boa. Quanto maior a sensibilidade aos juros, maior pode ser a variação de preço antes do vencimento.",
                    "Prazo longo não elimina emissor nem marcação a mercado. Em geral, aumenta a exposição à mudança de juros."),
                q("l4-q16", "— Rating", "Uma agência atribui rating elevado a um emissor. Como Bia deve usar essa informação?", "Avaliação de crédito", "A",
                    "Como um dado de análise de crédito, sem tratá-lo como garantia de pagamento ou recomendação de compra", "Como garantia de que o investimento não terá perdas", "Como substituto para ler emissor, prazo e riscos do produto",
                    "Certo. Rating é opinião de risco e pode mudar. Ele complementa, mas não encerra, a análise do emissor e do produto.",
                    "Nenhuma classificação elimina risco ou substitui as informações do investimento. Avaliação de crédito é uma peça do conjunto."),
                q("l4-q17", "— Exposição cambial", "Bia investe em um ativo cujo resultado é medido em dólar, mas seus gastos são em reais. Que risco adicional ela passa a ter?", "Risco cambial", "B",
                    "Variação da taxa de câmbio entre real e dólar", "Garantia automática contra inflação brasileira", "Eliminação do risco do ativo estrangeiro",
                    "Isso. Mesmo que o ativo externo não mude de preço em dólar, a conversão para reais pode alterar o resultado percebido.",
                    "Exposição internacional pode diversificar, mas não elimina os riscos do ativo e acrescenta a influência do câmbio."),
                q("l4-q18", "— Rebalanceamento com custo", "Ao rebalancear a carteira, por que Bia deve considerar custos e tributação antes de vender ativos?", "Monitoramento de carteira", "C",
                    "Porque operações podem ter taxas e impactos tributários que afetam o resultado líquido", "Porque rebalancear garante que nunca haverá perdas", "Porque todo rebalanceamento é proibido após o primeiro aporte",
                    "Correto. Rebalancear pode fazer sentido, mas a decisão precisa olhar também o custo de executar os ajustes.",
                    "Acompanhamento não é proibido nem garante lucro. Custos e impostos fazem parte da análise prática."),
                q("l4-q19", "— Viés de desempenho recente", "Um ativo subiu muito nos últimos três meses e Bia quer concentrar todo o dinheiro nele. Qual cuidado é mais adequado?", "Decisão baseada em histórico", "A",
                    "Entender que desempenho recente não garante repetição e comparar a decisão com o plano da carteira", "Assumir que alta recente elimina o risco de queda", "Ignorar objetivos e prazo porque o gráfico está favorável",
                    "Boa. Histórico é informação, não promessa. Perseguir alta recente pode aumentar concentração e afastar a carteira do objetivo.",
                    "Movimento passado não remove risco. Objetivo, diversificação e horizonte continuam válidos mesmo em períodos de alta."),
                q("l4-q20", "— Comparação risco-retorno", "Em uma comparação hipotética entre dois ativos de risco semelhante, um oferece retorno esperado menor e custo maior que o outro. Qual conclusão inicial é razoável?", "Princípio de dominância", "B",
                    "O ativo menos vantajoso merece investigação antes de entrar na carteira, pois pode estar dominado na comparação", "O custo maior prova que ele é automaticamente melhor", "Risco e retorno nunca devem ser comparados",
                    "Certo. Comparar risco, retorno esperado e custo ajuda a identificar alternativas pouco eficientes. A decisão real ainda exige olhar liquidez e objetivo.",
                    "Custos não são prova de qualidade, e risco-retorno é justamente uma comparação básica de investimentos."))
            ,
            level(5, "Desafio CPA", "🎓", "coral",
                "Aplique os conceitos em casos integrados com linguagem mais técnica.",
                "Miss?o: voc? ? o primeiro ponto de apoio do cliente",
                "Rafael tem R$ 10.000, objetivos diferentes e d?vidas sobre produtos, riscos e conduta. O desafio ? acolher, organizar informa??es, explicar limites e encaminhar quando necess?rio.",
                "Rafael concluiu o desafio entendendo atendimento inicial, suitability, transpar?ncia, prote??o de dados, preven??o a fraudes, PLD/FT e limites de atua??o. Essa postura conecta conhecimento t?cnico com conduta profissional para a CPA.",
                q("l5-q1", "— Limite de atuação da CPA", "Rafael pergunta: \"Com meus R$ 10 mil, diga exatamente quanto colocar em cada produto\". Qual é a conduta mais adequada para uma pessoa com CPA no atendimento inicial?", "Atendimento inicial e encaminhamento", "B",
                    "Explicar características e riscos básicos, organizar as informações necessárias e encaminhar a recomendação personalizada ao profissional habilitado para isso", "Definir uma carteira detalhada apenas pela taxa anunciada no dia", "Prometer que um produto específico será adequado independentemente do perfil",
                    "Correto. A CPA atua no contato inicial e na prestação de informações primárias. Recomendação individual detalhada exige o escopo e a habilitação apropriados.",
                    "Taxa isolada e promessa de adequação não substituem a análise profissional de objetivo, risco, prazo e situação do cliente."),
                q("l5-q2", "Caso integrado · emissor e garantia", "Ao avaliar um CDB, qual afirmação sobre o emissor e a proteção é mais precisa?", "Risco de crédito e cobertura do FGC", "C",
                    "É uma obrigação da instituição emissora; eventual cobertura depende das regras e limites vigentes do FGC", "É uma obrigação do governo federal sem risco de crédito", "Todo investimento financeiro tem cobertura integral do FGC",
                    "Isso. O risco de crédito está ligado ao emissor. A cobertura do FGC se aplica somente a produtos elegíveis e conforme regras e limites vigentes.",
                    "CDB é obrigação do emissor, não do governo. O FGC não cobre todos os investimentos nem significa cobertura ilimitada."),
                q("l5-q3", "Caso integrado · fundo de investimento", "Rafael avalia um fundo para diversificar. Qual informação ajuda a entender os riscos e custos antes de investir?", "Leitura das características do fundo", "A",
                    "Política de investimento, riscos, taxas, prazo de resgate e documentos do fundo", "Somente o retorno do último mês", "Apenas a quantidade de cotistas",
                    "Boa análise. Política, riscos, custos e condições de resgate ajudam a avaliar se o fundo combina com o objetivo.",
                    "Um retorno recente isolado não explica estratégia, risco, custos nem prazo de resgate. É preciso analisar as características do fundo."),
                q("l5-q4", "— Atualização da adequação", "Seis meses depois, Rafael perde parte da renda e passa a depender mais da reserva. O que deve acontecer com as informações usadas para avaliar a adequação dos produtos?", "Monitoramento de suitability", "B",
                    "Devem ser revisadas, porque objetivo, situação financeira e necessidade de liquidez mudaram", "Devem ser ignoradas, pois o perfil preenchido uma vez nunca muda", "Devem ser substituídas apenas pelo retorno que a carteira teve no período",
                    "Boa. Suitability não é uma fotografia eterna. Mudanças relevantes na vida podem alterar a compatibilidade de uma alocação com o cliente.",
                    "Retorno passado não atualiza objetivos ou capacidade de perda. As informações da clientela precisam refletir a situação atual."),
                q("l5-q5", "— Transparência de remuneração", "Rafael pergunta se a instituição recebe remuneração diferente para distribuir produtos semelhantes. Qual conduta é mais adequada?", "Conflito de interesses e transparência", "C",
                    "Dar informação clara e transparente sobre a remuneração e manter a análise de adequação do produto", "Omitir a informação para evitar que ele questione a escolha", "Escolher automaticamente o produto com maior remuneração para a instituição",
                    "Certo. Transparência ajuda a administrar conflitos de interesse e protege a confiança no atendimento.",
                    "Comissão não pode substituir a análise do interesse e das necessidades da pessoa investidora. Omissão reduz a qualidade da relação."),
                q("l5-q6", "— Cadastro e proteção de dados", "Rafael não informa a origem de recursos nem atualiza seus dados de renda, mas pede atendimento imediato. Qual é a postura correta?", "Conheça seu cliente (KYC)", "A",
                    "Solicitar e registrar as informações necessárias pelos canais adequados, protegendo os dados e seguindo os procedimentos internos", "Preencher os dados com suposições para acelerar a operação", "Usar o cadastro de outro cliente com perfil parecido",
                    "Exato. Cadastro adequado ajuda a conhecer o cliente, avaliar coerência das operações e cumprir regras de atendimento e proteção de dados.",
                    "Supor ou reutilizar dados de outra pessoa compromete a análise e a confidencialidade. Pressa não justifica dados incompletos."),
                q("l5-q7", "Caso CPA - risco de mercado", "Um titulo prefixado longo pode cair de preco se os juros de mercado subirem. Que risco Rafael deve entender?", "Risco de mercado", "B",
                    "Risco de oscilacao de preco antes do vencimento", "Risco de o FGC deixar de cobrir acoes", "Risco de liquidez diaria obrigatoria",
                    "Exato. A marcacao a mercado afeta o preco de venda antes do vencimento.",
                    "O ponto aqui nao e garantia, e preco. A microdica e relacionar juros, prazo e oscilacao."),
                q("l5-q8", "Caso CPA - fundo", "Rafael escolhe um fundo olhando apenas a rentabilidade passada. Qual alerta tecnico e necessario?", "Rentabilidade passada", "C",
                    "Rentabilidade passada nao garante resultado futuro", "Resultado passado elimina risco de mercado", "Historico dispensa leitura dos documentos",
                    "Certo. Historico ajuda na analise, mas nao substitui risco, politica, custos e prazo.",
                    "Historico seduz porque parece prova. A microdica e tratar passado como dado, nao promessa."),
                q("l5-q9", "— Publicidade responsável", "Uma campanha diz: \"Este fundo é perfeito para qualquer pessoa e vai render como no último ano\". Qual ajuste é necessário para uma comunicação responsável?", "Comunicação de investimentos", "A",
                    "Informar riscos, público/objetivo compatível e deixar claro que rentabilidade passada não garante resultado futuro", "Manter a promessa, desde que a campanha tenha letras pequenas no rodapé", "Retirar apenas o nome do fundo, preservando a garantia de retorno",
                    "Boa. Comunicação clara evita transformar dado histórico em promessa e ajuda a pessoa investidora a compreender limitações do produto.",
                    "Letras pequenas não corrigem uma promessa enganosa. Risco, adequação e incerteza futura precisam aparecer de forma compreensível."),
                q("l5-q10", "Caso CPA - credito", "Rafael compara CDBs de bancos diferentes. O que representa risco de credito nesse caso?", "Risco de credito", "B",
                    "A possibilidade de o emissor nao honrar a obrigacao", "A variacao diaria obrigatoria das acoes", "A taxa de administracao de um fundo multimercado",
                    "Correto. Em CDB, o emissor importa; garantia e limite devem ser avaliados junto.",
                    "Aqui o foco e quem deve pagar. A microdica e perguntar: quem e o emissor e qual sua solidez?"),
                q("l5-q11", "Caso CPA - conduta", "Rafael pede uma promessa de rentabilidade para aceitar o investimento. O que o assessor deve evitar?", "Conduta e promessa de retorno", "C",
                    "Prometer retorno futuro como se fosse garantido", "Explicar riscos, custos e cenarios possiveis", "Registrar as informacoes usadas na recomendacao",
                    "Exato. Boa conduta evita promessa indevida e comunica riscos de forma clara.",
                    "Cliente pode pedir certeza, mas investimento envolve risco. A microdica e explicar, nao prometer."),
                q("l5-q12", "Caso CPA - decisao final", "Depois de separar reserva e longo prazo, Rafael aceita mais risco apenas para a parcela de longo prazo. Qual conclusao e mais tecnica?", "Carteira por objetivos", "A",
                    "Cada parcela pode ter produto diferente conforme prazo, liquidez e risco", "Toda carteira deve ter um unico produto para simplificar", "Reserva de emergencia e longo prazo sempre exigem o mesmo risco",
                    "Missao CPA reforcada. A recomendacao adequada segmenta objetivos e compara produtos por risco, liquidez, custo e horizonte.",
                    "Simplificar demais pode prejudicar adequacao. A microdica e dividir a carteira por finalidade."),
                q("l5-q13", "— Sinal de alerta e PLD/FT", "Uma operação é incompatível com o perfil conhecido de Rafael, e ele evita esclarecer a origem dos recursos. Qual conduta é adequada?", "Prevenção à lavagem de dinheiro e financiamento do terrorismo", "B",
                    "Seguir os procedimentos internos de análise e comunicação aplicáveis, sem avisar o cliente de uma eventual comunicação suspeita", "Ignorar o caso porque o cliente diz que tem pressa", "Acusar Rafael de crime diretamente durante o atendimento",
                    "Correto. A instituição deve tratar sinais de alerta conforme políticas e regras de PLD/FT, com registro e confidencialidade adequados.",
                    "Pressa não elimina controles, e acusar o cliente não é o procedimento. A conduta deve ser técnica, discreta e baseada em normas internas."),
                q("l5-q14", "— LGPD e sigilo", "Uma colega pede os dados de renda de Rafael para enviar uma oferta genérica, sem relação com o atendimento dele. O que fazer?", "Proteção de dados", "C",
                    "Não compartilhar os dados sem necessidade e base apropriada; usar informações somente para finalidades autorizadas", "Enviar os dados por mensagem pessoal, pois ambos trabalham na instituição", "Publicar os dados sem nome em um grupo externo para pedir opiniões",
                    "Isso. Dados financeiros exigem confidencialidade e tratamento compatível com a finalidade. Acesso interno não é autorização ilimitada.",
                    "Mensagens pessoais e grupos externos expõem dados indevidamente. Proteção de dados é parte da conduta profissional."),
                q("l5-q15", "— Conflito de interesses", "A instituição oferece um bônus maior pela venda de um produto que não combina com a necessidade de liquidez de Rafael. Qual atitude é correta?", "Ética profissional", "A",
                    "Não deixar a remuneração direcionar uma oferta inadequada e comunicar de forma transparente eventuais conflitos", "Priorizar o bônus, pois a decisão final é sempre só do cliente", "Omitir a carência para tornar o produto mais atrativo",
                    "Certo. Interesse comercial não justifica esconder informação ou ignorar a adequação ao objetivo do cliente.",
                    "O cliente só decide bem quando recebe informações claras. Omissão e incentivo inadequado violam a boa conduta."),
                q("l5-q16", "— Fraude eletrônica", "Rafael recebe uma ligação de alguém que pede senha e token para \"cancelar uma aplicação suspeita\". Qual orientação é mais segura?", "Segurança digital", "B",
                    "Não fornecer senhas ou tokens, encerrar o contato e procurar os canais oficiais da instituição", "Informar o token rapidamente para evitar bloqueio da conta", "Enviar uma foto do cartão e do documento para confirmar identidade",
                    "Exato. Senhas e códigos de autenticação são sigilosos. Conferir diretamente em canal oficial reduz o risco de engenharia social.",
                    "Golpistas usam urgência para obter credenciais. Instituições não devem pedir senhas ou tokens por contato inesperado."),
                q("l5-q17", "— Pilares ESG", "Qual exemplo está mais ligado ao pilar de governança (G) em uma empresa?", "ESG", "C",
                    "Transparência, controles internos e qualidade das práticas de gestão", "Redução de emissões de gases de efeito estufa", "Programas de diversidade e segurança do trabalho",
                    "Certo. Governança trata de como a organização é dirigida, controlada e presta contas. Ambiente e questões sociais são outros pilares.",
                    "Emissões se relacionam ao aspecto ambiental; diversidade e segurança do trabalho, ao social. Governança envolve controles e gestão."),
                q("l5-q18", "— Produto com rótulo ESG", "Um produto usa a palavra \"ESG\" no nome. O que Rafael deve verificar antes de concluir que ele atende sua preferência?", "Análise de investimento ESG", "A",
                    "Estratégia, política de investimento, critérios utilizados, riscos e documentos do produto", "Apenas a cor verde da campanha publicitária", "Se o produto promete retorno superior ao mercado",
                    "Boa. O rótulo não substitui documentação e método. Investimentos ESG também têm riscos, custos e possíveis limitações.",
                    "Marketing visual e promessa de retorno não comprovam estratégia ESG. A análise deve olhar o que o produto efetivamente faz."),
                q("l5-q19", "— Informação privilegiada", "Uma pessoa conta a Rafael, antes de divulgação pública, que sua empresa fará uma aquisição relevante. O que ele deve evitar?", "Ética e integridade de mercado", "B",
                    "Negociar o ativo ou repassar a informação para que outra pessoa negocie", "Acompanhar o comunicado oficial quando ele for divulgado ao mercado", "Procurar orientação pelos canais de compliance da instituição, quando aplicável",
                    "Correto. Usar ou repassar informação relevante ainda não pública pode caracterizar conduta ilícita no mercado de capitais.",
                    "Informações públicas e orientação de compliance são caminhos corretos. O problema é tirar vantagem de informação não divulgada."),
                q("l5-q20", "— Caso integrado de atendimento", "Rafael quer usar o mesmo dinheiro para emergência, viagem em oito meses e longo prazo. Seus dados estão desatualizados. Qual sequência é mais adequada no atendimento inicial?", "Atendimento, adequação e clareza", "C",
                    "Atualizar informações, separar objetivos e prazos, explicar características/riscos básicos e encaminhar recomendação personalizada quando necessária", "Escolher o produto com maior taxa anunciada e aplicar todo o valor nele", "Dizer que todos os investimentos servem igualmente para qualquer objetivo",
                    "Missão concluída. Bom atendimento combina dados atualizados, escuta, informação clara, limites de atuação e encaminhamento adequado.",
                    "Taxa isolada e tratamento igual para objetivos diferentes são atalhos perigosos. Cada parcela precisa ser entendida antes de qualquer indicação.\n\n---"))

        );
    }
}
